# docker build --progress plain -t gitlab-master.nvidia.com/sanggill/bigvgan:nemo .
# docker push gitlab-master.nvidia.com/sanggill/bigvgan:nemo
FROM nvcr.io/nvidian/rlangman-nemo-codec-inference:dev
# RUN apt update && apt install -y libsndfile1 ffmpeg
# Set the working directory for packages built from source
WORKDIR /app
# install torchaudio, need to build from source (missing from nvcr image)
# RUN git clone https://github.com/pytorch/audio
# RUN MAX_JOBS=4 pip install -v -e /app/audio --no-use-pep517
#############################
# additional packages used by BigVGAN
#############################
RUN pip install cython auraloss pesq gputil descript-audio-codec librosa pytorch_warmup